import Link from "next/link";

import { signInWithGoogle, signUp } from "@/lib/auth/actions";
import { AuthFrame } from "@/components/auth-frame";
import { GoogleIcon } from "@/components/icons";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default async function SignUpPage({ searchParams }: { searchParams: Promise<{ error?: string; sent?: string }> }) {
  const params = await searchParams;
  const errorMessage = params.error === "email" ? "Enter a valid email address." : params.error === "password" ? "Your password must contain at least 8 characters." : params.error === "profile" ? "Check your name and phone number, then try again." : params.error === "signup" ? "We could not create your account. This email may already be registered." : params.error === "oauth" ? "Google sign-up could not be completed. Try again or continue with email." : null;
  return <AuthFrame><div className="w-full max-w-md"><div className="mb-8"><p className="font-mono text-xs font-bold uppercase tracking-[0.18em] text-muted-foreground">Customer account</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight text-balance">Create account</h1><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">Save your delivery details and keep every 1968 Clothing order within reach.</p></div><div className="space-y-5">{params.sent === "1" && <Alert><AlertDescription>Check your email to confirm your account and finish registration.</AlertDescription></Alert>}{errorMessage && <Alert variant="destructive"><AlertDescription>{errorMessage}</AlertDescription></Alert>}<form action={signInWithGoogle}><Button variant="outline" type="submit" className="h-12 w-full gap-3"><GoogleIcon size={17} />Continue with Google</Button></form><div className="flex items-center gap-3" aria-label="or register with email"><span className="h-px flex-1 bg-border" /><span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">or register with email</span><span className="h-px flex-1 bg-border" /></div><form action={signUp} className="space-y-5"><div className="space-y-2"><Label htmlFor="email">Email address</Label><Input id="email" name="email" type="email" autoComplete="email" maxLength={254} required placeholder="you@example.com" className="h-12" /></div><div className="space-y-2"><Label htmlFor="password">Password <span className="font-normal text-muted-foreground">(8+ characters)</span></Label><Input id="password" name="password" type="password" autoComplete="new-password" minLength={8} required placeholder="••••••••" className="h-12" /></div><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="display_name">Full name <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="display_name" name="display_name" autoComplete="name" maxLength={100} placeholder="Juan Dela Cruz" className="h-12" /></div><div className="space-y-2"><Label htmlFor="phone">Phone <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="phone" name="phone" type="tel" autoComplete="tel" maxLength={32} placeholder="0917 123 4567" className="h-12" /></div></div><Button type="submit" className="h-12 w-full">Create account</Button></form></div><p className="mt-8 border-t border-border pt-6 text-sm text-muted-foreground">Already have an account? <Link href="/login" className="font-semibold text-foreground underline-offset-4 hover:underline">Sign in</Link></p></div></AuthFrame>;
}
